# roles/web/tasks/main.yml
---
- name: Install Apache
  yum: pkg={{item}} state=installed
  with_items:
    - httpd
    - php
    - php-xml
    - php-mysql

- name: Start Apache service
  service: name=httpd state=running enabled=yes

- name: Configure firewall 
  firewalld: service=http state=enabled permanent=no 
  
- name: Configure firewall (permanent)
  firewalld: service=http state=enabled permanent=yes
